/-
What the proofs actually rest on.

`scripts/verify.sh` runs this file and stores the output.  Every theorem below
should depend on nothing beyond Lean's three standard axioms —
`propext`, `Classical.choice`, `Quot.sound` — and on no axiom this project
declares, of which there are none.
-/
import Proofs

open Planner

#print axioms Planner.ground_wf
#print axioms Planner.ground_plan_sound
#print axioms Planner.groundedOps_instance
#print axioms Planner.ground_ops_instance
#print axioms Planner.groundedOps_complete
#print axioms Planner.ground_names_instance
#print axioms Planner.ground_names_instance_pruned
#print axioms Planner.ground_names_goal
#print axioms Planner.unnamed_false
#print axioms Planner.reachable_abstracts
#print axioms Planner.prune_preserves
#print axioms Planner.relevance_cases
#print axioms Planner.stepView
#print axioms Planner.admissibleOn_of_lifted
#print axioms Planner.goalAwareOn_of_lifted
#print axioms Planner.consistentOn_of_lifted
#print axioms Planner.ImprovedProof.admissible
#print axioms Planner.Lifted.Ferry.improved_consistent_of_pinned
#print axioms Planner.Lifted.Ferry.improved_goalAware_of_pinned
#print axioms Planner.Lifted.Miconic.improved_consistent_of_pinned
#print axioms Planner.Lifted.Miconic.improved_goalAware_of_pinned
#print axioms Planner.Lifted.Childsnack.improved_consistent_of_pinned
#print axioms Planner.Lifted.Childsnack.improved_goalAware_of_pinned
#print axioms Planner.Lifted.Spanner.improved_consistentOn
#print axioms Planner.Lifted.Spanner.improved_goalAwareOn
#print axioms Planner.Lifted.Spanner.improved_admissibleOn
#print axioms Planner.Lifted.Spanner.computes
#print axioms Planner.Lifted.Spanner.compiled_goalAwareOn
#print axioms Planner.Lifted.Spanner.compiled_consistentOn
#print axioms Planner.Lifted.Spanner.compiled_admissibleOn
#print axioms Planner.Lifted.Transport.improved_consistentOn
#print axioms Planner.Lifted.Transport.improved_goalAwareOn
#print axioms Planner.Lifted.Transport.improved_admissibleOn
#print axioms Planner.Lifted.Transport.computes
#print axioms Planner.Lifted.Transport.compiled_goalAwareOn
#print axioms Planner.Lifted.Transport.compiled_consistentOn
#print axioms Planner.Lifted.Transport.compiled_admissibleOn
#print axioms Planner.Lifted.Spanner.dataMatches
#print axioms Planner.Lifted.Spanner.dataMatches_ground
#print axioms Planner.Lifted.Spanner.improved_admissible_of_shape
#print axioms Planner.Lifted.Transport.dataMatches
#print axioms Planner.Lifted.Transport.dataMatches_ground
#print axioms Planner.Lifted.Transport.improved_admissible_of_shape
#print axioms Planner.Graph.mem_adj_of_static
#print axioms Planner.Lifted.Satellite.improved_goalAwareOn
#print axioms Planner.Lifted.Satellite.improved_consistentOn
#print axioms Planner.Lifted.Satellite.improved_admissibleOn
#print axioms Planner.Lifted.Satellite.computes
#print axioms Planner.Lifted.Satellite.compiled_admissibleOn
#print axioms Planner.Lifted.Satellite.dataMatches
#print axioms Planner.Lifted.Satellite.dataMatches_ground
#print axioms Planner.Lifted.Satellite.improved_admissible_of_shape
#print axioms Planner.Lifted.Satellite.improved_admissible_of_pinned
#print axioms Planner.Lifted.Satellite.cost_pos
#print axioms Planner.Lifted.Satellite.image_goal_data
#print axioms Planner.Lifted.Satellite.pointing_goal_data
#print axioms Planner.Lifted.Satellite.instruments_congr
#print axioms Planner.Lifted.Satellite.turn_instruments
#print axioms Planner.Lifted.Satellite.turn_frame_images
#print axioms Planner.Lifted.Satellite.pointing_goalAtom_inj
#print axioms Planner.Lifted.Satellite.turn_frame_pointing_other
#print axioms Planner.Lifted.Satellite.turn_old_false
#print axioms Planner.Lifted.Satellite.turn_preserves_unmet_other
#print axioms Planner.Lifted.Satellite.turn_unmetPointing_bound
#print axioms Planner.Lifted.Satellite.turn_step_of_bound
#print axioms Planner.Lifted.Spanner.goalAtom_mem
#print axioms Planner.Lifted.Transport.goalAtom_mem
#print axioms Planner.Lifted.Transport.nodes_ok
#print axioms Planner.Lifted.Satellite.image_goalAtom_mem
#print axioms Planner.Lifted.Satellite.pointing_goalAtom_mem
#print axioms Planner.Lifted.Transport.inv_preserved
#print axioms Planner.Lifted.Transport.initInv_of_check
#print axioms Planner.Lifted.Transport.mem_vehAt
#print axioms Planner.Lifted.Transport.mem_vehAt_total
#print axioms Planner.Lifted.Transport.vehLoc_eq
#print axioms Planner.Lifted.Transport.pkg_exists
#print axioms Planner.Distances.get_of_ge
#print axioms Planner.Lifted.Transport.drive_step
#print axioms Planner.Lifted.Transport.road_edge
#print axioms Planner.Lifted.Transport.pkg_data
#print axioms Planner.Lifted.Transport.pkg_unique
#print axioms Planner.Lifted.Transport.pickup_step
#print axioms Planner.Lifted.Transport.drop_step
#print axioms Planner.Lifted.Transport.schemaStep_of_ops
#print axioms Planner.Lifted.Transport.improved_admissible
#print axioms Planner.OpFactsAdd
#print axioms Planner.opFacts_raw_add
#print axioms Planner.Lifted.Spanner.inv_preserved
#print axioms Planner.Lifted.Spanner.mem_menAt
#print axioms Planner.Lifted.Spanner.menLoc_mem
#print axioms Planner.Lifted.Spanner.nuts_data
#print axioms Planner.Lifted.Spanner.spanners_data
#print axioms Planner.Lifted.Spanner.spanner_unique
#print axioms Planner.Lifted.Spanner.nut_unique
#print axioms Planner.Lifted.Spanner.walk_step
#print axioms Planner.Lifted.Spanner.pickup_step
#print axioms Planner.Lifted.Spanner.tighten_step
#print axioms Planner.Lifted.Spanner.schemaStep_of_ops
#print axioms Planner.Lifted.Spanner.improved_admissible
#print axioms Planner.Lifted.Spanner.nuts_nodup
#print axioms Planner.Lifted.Spanner.spanners_nodup
#print axioms Planner.pruned_op
#print axioms Planner.add_of_trim
#print axioms Planner.opFacts_pruned_add
#print axioms Planner.Lifted.Transport.adds_of_raw
#print axioms Planner.Lifted.Transport.adds_of_pruned
#print axioms Planner.Lifted.Transport.improved_admissible'
#print axioms Planner.Lifted.Transport.packages_nodup
#print axioms Planner.Lifted.Floortile.instance_shape
#print axioms Planner.Lifted.Floortile.liftedGoalAware
#print axioms Planner.Lifted.Floortile.effect_of_schema
#print axioms Planner.Lifted.Floortile.improved_admissibleOn
#print axioms Planner.Lifted.Floortile.computes
#print axioms Planner.Lifted.Floortile.dataMatches
#print axioms Planner.Lifted.Floortile.dataMatches_ground
#print axioms Planner.Lifted.Floortile.inv_preserved
#print axioms Planner.Lifted.Floortile.initInv_of_check
#print axioms Planner.Lifted.simple_admissibleOn
#print axioms Planner.Lifted.Miconic.improved_admissibleOn
#print axioms Planner.Lifted.Miconic.computes
#print axioms Planner.Lifted.Miconic.improved_admissible_of_pinned
#print axioms Planner.Lifted.Miconic.ex_admissible
#print axioms Planner.Lifted.Ferry.improved_admissibleOn
#print axioms Planner.Lifted.Ferry.computes
#print axioms Planner.Lifted.Ferry.improved_admissible_of_pinned
#print axioms Planner.Lifted.Ferry.ex_admissible
#print axioms Planner.Lifted.Childsnack.improved_admissibleOn
#print axioms Planner.Lifted.Childsnack.computes
#print axioms Planner.Lifted.Childsnack.improved_admissible_of_pinned
#print axioms Planner.Lifted.Childsnack.ex_admissible
#print axioms Planner.assemble_apply
#print axioms Planner.factIndex_name
#print axioms Planner.astar_sound
#print axioms Planner.astar_optimal
#print axioms Planner.astar_complete
#print axioms Planner.astarCompiled_sound
#print axioms Planner.astarCompiled_optimal
#print axioms Planner.astarCompiled_complete
#print axioms Planner.astarCompiled_mono
#print axioms Planner.astar_terminates
#print axioms Planner.astar_decides
#print axioms Planner.loop_complete
#print axioms Planner.loop_optimal
#print axioms Planner.frontier_bound
#print axioms Planner.admissible_of_goalAware_consistent
#print axioms Planner.Task.admissible
#print axioms Planner.Task.maxMissingOf_admissible
#print axioms Planner.ExampleHeuristics.Blocksworld.improved_admissible
#print axioms Planner.ExampleHeuristics.Childsnack.improved_admissible
#print axioms Planner.ExampleHeuristics.Floortile.improved_admissible
#print axioms Planner.ExampleHeuristics.Miconic.improved_admissible
#print axioms Planner.ExampleHeuristics.Satellite.improved_admissible
#print axioms Planner.ExampleHeuristics.Sokoban.improved_admissibleOn_of_schema
#print axioms Planner.ExampleHeuristics.Spanner.improved_admissible
#print axioms Planner.ExampleHeuristics.Miconic.improved_goalAware
#print axioms Planner.ExampleHeuristics.Sokoban.improved_goalAware
#print axioms Planner.ExampleHeuristics.Sokoban.improved_consistentOn
#print axioms Planner.ExampleHeuristics.Floortile.improved_goalAware
#print axioms Planner.Op.test_apply
#print axioms Planner.NodesOK.planTo_valid
#print axioms Planner.OpenList.pop?_spec
#print axioms Planner.OpenList.pop?_none
#print axioms Planner.Distances.le_walk
#print axioms Planner.blind_admissible

#print axioms Planner.ExampleHeuristics.Blocksworld.simple_admissible
#print axioms Planner.ExampleHeuristics.Childsnack.simple_admissible
#print axioms Planner.ExampleHeuristics.Ferry.simple_admissible
#print axioms Planner.ExampleHeuristics.Floortile.simple_admissible
#print axioms Planner.ExampleHeuristics.Miconic.simple_admissible
#print axioms Planner.ExampleHeuristics.Rovers.simple_admissible
#print axioms Planner.ExampleHeuristics.Satellite.simple_admissible
#print axioms Planner.ExampleHeuristics.Sokoban.simple_admissible
#print axioms Planner.ExampleHeuristics.Spanner.simple_admissible
#print axioms Planner.ExampleHeuristics.Transport.simple_admissible

-- The schema-level statements: admissibility with nothing assumed about the
-- heuristic's own counters, only about what the domain's schemas do.
#print axioms Planner.Task.maxMissingOf_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Blocksworld.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Blocksworld.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Blocksworld.improved_goalAware_of_schema
#print axioms Planner.ExampleHeuristics.Blocksworld.improved_admissibleOn_of_schema
#print axioms Planner.Lifted.Rovers.improved_goalAware
#print axioms Planner.Lifted.Sokoban.simple_goalAware
#print axioms Planner.ExampleHeuristics.Rovers.improved_admissibleOn_of_schema
#print axioms Planner.Lifted.Rovers.sampleSoil_schemaStep
#print axioms Planner.Lifted.Rovers.sampleRock_schemaStep
#print axioms Planner.Lifted.Rovers.takeImage_schemaStep
#print axioms Planner.Lifted.Rovers.navigate_schemaStep
#print axioms Planner.Lifted.Rovers.schemaStep_of_op
#print axioms Planner.Lifted.Rovers.reach_oneAt
#print axioms Planner.Lifted.Rovers.schemaStep_of_reach
#print axioms Planner.Lifted.Rovers.improved_admissible_of_pinned
#print axioms Planner.Lifted.Rovers.soilGoals_nodup
#print axioms Planner.Lifted.Rovers.rockGoals_nodup
#print axioms Planner.Lifted.Rovers.imageGoals_nodup
#print axioms Planner.Lifted.Rovers.addsKept
#print axioms Planner.Lifted.Rovers.at_relevant
#print axioms Planner.Lifted.Rovers.lone_add_relevant
#print axioms Planner.Lifted.Blocksworld.improved_admissible
#print axioms Planner.Lifted.Blocksworld.addsKept_true
#print axioms Planner.Lifted.Blocksworld.improved_admissible_of_pinned
#print axioms Planner.ExampleHeuristics.Ferry.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Ferry.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Ferry.improved_goalAware_of_schema
#print axioms Planner.ExampleHeuristics.Floortile.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Floortile.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Floortile.improved_goalAware_of_schema
#print axioms Planner.ExampleHeuristics.Miconic.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Miconic.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Miconic.improved_goalAware_of_schema
#print axioms Planner.ExampleHeuristics.Childsnack.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Childsnack.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Childsnack.improved_goalAware_of_schema
#print axioms Planner.ExampleHeuristics.Rovers.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Rovers.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Rovers.improved_goalAware_of_schema
#print axioms Planner.ExampleHeuristics.Satellite.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Satellite.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Satellite.improved_goalAware_of_schema
#print axioms Planner.ExampleHeuristics.Sokoban.improved_consistentOn_of_schema
#print axioms Planner.ExampleHeuristics.Sokoban.improved_goalAware_of_schema
#print axioms Planner.Lifted.Sokoban.simple_admissible_of_pinned
#print axioms Planner.Lifted.Sokoban.move_schemaStep
#print axioms Planner.Lifted.Sokoban.push_schemaStep
#print axioms Planner.Lifted.Sokoban.schemaStep_of_ops
#print axioms Planner.Lifted.Sokoban.inv_step
#print axioms Planner.Lifted.Sokoban.frameAddsKept
#print axioms Planner.Lifted.Sokoban.move_reads_relevant
#print axioms Planner.Lifted.Sokoban.reach_inv
#print axioms Planner.Lifted.Sokoban.schemaStep_of_reach
#print axioms Planner.Lifted.Sokoban.improved_admissible_of_certified
#print axioms Planner.Lifted.Blocksworld.certificate_sound
#print axioms Planner.Lifted.Blocksworld.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Blocksworld.improved_consistent_of_certificate
#print axioms Planner.Lifted.Blocksworld.improved_proof_of_certificate
#print axioms Planner.Lifted.Blocksworld.improved_admissible_of_certificate
#print axioms Planner.Lifted.Floortile.certificate_sound
#print axioms Planner.Lifted.Floortile.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Floortile.improved_consistent_of_certificate
#print axioms Planner.Lifted.Floortile.improved_proof_of_certificate
#print axioms Planner.Lifted.Floortile.improved_admissible_of_certificate
#print axioms Planner.Lifted.Transport.certificate_sound
#print axioms Planner.Lifted.Transport.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Transport.improved_consistent_of_certificate
#print axioms Planner.Lifted.Transport.improved_proof_of_certificate
#print axioms Planner.Lifted.Transport.improved_admissible_of_certificate
#print axioms Planner.Lifted.Rovers.certificate_sound
#print axioms Planner.Lifted.Rovers.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Rovers.improved_consistent_of_certificate
#print axioms Planner.Lifted.Rovers.improved_proof_of_certificate
#print axioms Planner.Lifted.Rovers.improved_admissible_of_certificate
#print axioms Planner.Lifted.Sokoban.certificate_sound
#print axioms Planner.Lifted.Sokoban.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Sokoban.improved_consistent_of_certificate
#print axioms Planner.Lifted.Sokoban.improved_proof_of_certificate
#print axioms Planner.Lifted.Sokoban.improved_admissible_of_certificate
#print axioms Planner.Lifted.Ferry.certificate_sound
#print axioms Planner.Lifted.Ferry.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Ferry.improved_consistent_of_certificate
#print axioms Planner.Lifted.Ferry.improved_proof_of_certificate
#print axioms Planner.Lifted.Ferry.improved_admissible_of_certificate
#print axioms Planner.Lifted.Miconic.certificate_sound
#print axioms Planner.Lifted.Miconic.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Miconic.improved_consistent_of_certificate
#print axioms Planner.Lifted.Miconic.improved_proof_of_certificate
#print axioms Planner.Lifted.Miconic.improved_admissible_of_certificate
#print axioms Planner.Lifted.Childsnack.certificate_sound
#print axioms Planner.Lifted.Childsnack.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Childsnack.improved_consistent_of_certificate
#print axioms Planner.Lifted.Childsnack.improved_proof_of_certificate
#print axioms Planner.Lifted.Childsnack.improved_admissible_of_certificate
#print axioms Planner.Lifted.Spanner.certificate_sound
#print axioms Planner.Lifted.Spanner.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Spanner.improved_consistent_of_certificate
#print axioms Planner.Lifted.Spanner.improved_proof_of_certificate
#print axioms Planner.Lifted.Spanner.improved_admissible_of_certificate
#print axioms Planner.Lifted.Satellite.certificate_sound
#print axioms Planner.Lifted.Satellite.improved_goalAware_of_certificate
#print axioms Planner.Lifted.Satellite.improved_consistent_of_certificate
#print axioms Planner.Lifted.Satellite.improved_proof_of_certificate
#print axioms Planner.Lifted.Satellite.improved_admissible_of_certificate
#print axioms Planner.Lifted.Sokoban.boxes_nodup
#print axioms Planner.noDuplicates_nodup
#print axioms Planner.forIn_ok_const
#print axioms Planner.forIn_ok_each
#print axioms Planner.validateProblem_objects_nodup
#print axioms Planner.validateDomain_constants_nodup
#print axioms Planner.Validated.no_shadow
#print axioms Planner.Validated.namesNodup
#print axioms Planner.goalTable_nodup
#print axioms Planner.goalTable_nodup_fact
#print axioms Planner.atomOf_mem_goal
#print axioms Planner.factNames_inj
#print axioms Planner.ExampleHeuristics.Sokoban.jointSound_of_check
#print axioms Planner.ExampleHeuristics.Spanner.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Spanner.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Spanner.improved_goalAware_of_schema
#print axioms Planner.ExampleHeuristics.Transport.improved_admissible_of_schema
#print axioms Planner.ExampleHeuristics.Transport.improved_consistent_of_schema
#print axioms Planner.ExampleHeuristics.Transport.improved_goalAware_of_schema
#print axioms Planner.Lifted.Floortile.improved_admissible
#print axioms Planner.Lifted.Floortile.improved_admissible_of_pinned
#print axioms Planner.Lifted.Floortile.schemaStep_of_ops
#print axioms Planner.Lifted.Floortile.paint_step
#print axioms Planner.Lifted.Floortile.move_step
#print axioms Planner.Lifted.Floortile.colour_step
#print axioms Planner.Lifted.Floortile.compiled_admissibleOn
#print axioms Planner.Lifted.Floortile.dataMatches_ground
#print axioms Planner.Lifted.Floortile.inv_preserved
#print axioms Planner.Lifted.Floortile.tiles_shape
#print axioms Planner.Lifted.Floortile.tiles_cover
#print axioms Planner.Reach.reachFrom_guarded
#print axioms Planner.Reach.reachFrom_least
#print axioms Planner.Reach.reachFrom_closed
#print axioms Planner.Reach.reachFrom_start
