/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Blocksworld

open Planner.Pddl

abbrev action0 : Action :=
  { name := "pickup",
    params := [{ name := "?ob", type := "object" }],
    pre := [{ pred := "clear", args := [.var "?ob"] }, { pred := "on-table", args := [.var "?ob"] }, { pred := "arm-empty", args := [] }],
    add := [{ pred := "holding", args := [.var "?ob"] }],
    del := [{ pred := "clear", args := [.var "?ob"] }, { pred := "on-table", args := [.var "?ob"] }, { pred := "arm-empty", args := [] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "putdown",
    params := [{ name := "?ob", type := "object" }],
    pre := [{ pred := "holding", args := [.var "?ob"] }],
    add := [{ pred := "clear", args := [.var "?ob"] }, { pred := "arm-empty", args := [] }, { pred := "on-table", args := [.var "?ob"] }],
    del := [{ pred := "holding", args := [.var "?ob"] }],
    cost := 1 }

abbrev action2 : Action :=
  { name := "stack",
    params := [{ name := "?ob", type := "object" }, { name := "?underob", type := "object" }],
    pre := [{ pred := "clear", args := [.var "?underob"] }, { pred := "holding", args := [.var "?ob"] }],
    add := [{ pred := "arm-empty", args := [] }, { pred := "clear", args := [.var "?ob"] }, { pred := "on", args := [.var "?ob", .var "?underob"] }],
    del := [{ pred := "clear", args := [.var "?underob"] }, { pred := "holding", args := [.var "?ob"] }],
    cost := 1 }

abbrev action3 : Action :=
  { name := "unstack",
    params := [{ name := "?ob", type := "object" }, { name := "?underob", type := "object" }],
    pre := [{ pred := "on", args := [.var "?ob", .var "?underob"] }, { pred := "clear", args := [.var "?ob"] }, { pred := "arm-empty", args := [] }],
    add := [{ pred := "holding", args := [.var "?ob"] }, { pred := "clear", args := [.var "?underob"] }],
    del := [{ pred := "on", args := [.var "?ob", .var "?underob"] }, { pred := "clear", args := [.var "?ob"] }, { pred := "arm-empty", args := [] }],
    cost := 1 }

abbrev actions : List Action := [action0, action1, action2, action3]

def domain : Domain :=
  { name := "blocksworld",
    requirements := [":strips"],
    types := [],
    constants := [],
    predicates := [{ name := "clear", params := [{ name := "?x", type := "object" }] }, { name := "on-table", params := [{ name := "?x", type := "object" }] }, { name := "arm-empty", params := [] }, { name := "holding", params := [{ name := "?x", type := "object" }] }, { name := "on", params := [{ name := "?x", type := "object" }, { name := "?y", type := "object" }] }],
    actions := actions }

end Planner.GeneratedDomains.Blocksworld
