/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Childsnack

open Planner.Pddl

abbrev action0 : Action :=
  { name := "make_sandwich_no_gluten",
    params := [{ name := "?s", type := "sandwich" }, { name := "?b", type := "bread-portion" }, { name := "?c", type := "content-portion" }],
    pre := [{ pred := "at_kitchen_bread", args := [.var "?b"] }, { pred := "at_kitchen_content", args := [.var "?c"] }, { pred := "no_gluten_bread", args := [.var "?b"] }, { pred := "no_gluten_content", args := [.var "?c"] }, { pred := "notexist", args := [.var "?s"] }],
    add := [{ pred := "at_kitchen_sandwich", args := [.var "?s"] }, { pred := "no_gluten_sandwich", args := [.var "?s"] }],
    del := [{ pred := "at_kitchen_bread", args := [.var "?b"] }, { pred := "at_kitchen_content", args := [.var "?c"] }, { pred := "notexist", args := [.var "?s"] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "make_sandwich",
    params := [{ name := "?s", type := "sandwich" }, { name := "?b", type := "bread-portion" }, { name := "?c", type := "content-portion" }],
    pre := [{ pred := "at_kitchen_bread", args := [.var "?b"] }, { pred := "at_kitchen_content", args := [.var "?c"] }, { pred := "notexist", args := [.var "?s"] }],
    add := [{ pred := "at_kitchen_sandwich", args := [.var "?s"] }],
    del := [{ pred := "at_kitchen_bread", args := [.var "?b"] }, { pred := "at_kitchen_content", args := [.var "?c"] }, { pred := "notexist", args := [.var "?s"] }],
    cost := 1 }

abbrev action2 : Action :=
  { name := "put_on_tray",
    params := [{ name := "?s", type := "sandwich" }, { name := "?t", type := "tray" }],
    pre := [{ pred := "at_kitchen_sandwich", args := [.var "?s"] }, { pred := "at", args := [.var "?t", .const "kitchen"] }],
    add := [{ pred := "ontray", args := [.var "?s", .var "?t"] }],
    del := [{ pred := "at_kitchen_sandwich", args := [.var "?s"] }],
    cost := 1 }

abbrev action3 : Action :=
  { name := "serve_sandwich_no_gluten",
    params := [{ name := "?s", type := "sandwich" }, { name := "?c", type := "child" }, { name := "?t", type := "tray" }, { name := "?p", type := "place" }],
    pre := [{ pred := "allergic_gluten", args := [.var "?c"] }, { pred := "ontray", args := [.var "?s", .var "?t"] }, { pred := "waiting", args := [.var "?c", .var "?p"] }, { pred := "no_gluten_sandwich", args := [.var "?s"] }, { pred := "at", args := [.var "?t", .var "?p"] }],
    add := [{ pred := "served", args := [.var "?c"] }],
    del := [{ pred := "ontray", args := [.var "?s", .var "?t"] }],
    cost := 1 }

abbrev action4 : Action :=
  { name := "serve_sandwich",
    params := [{ name := "?s", type := "sandwich" }, { name := "?c", type := "child" }, { name := "?t", type := "tray" }, { name := "?p", type := "place" }],
    pre := [{ pred := "not_allergic_gluten", args := [.var "?c"] }, { pred := "waiting", args := [.var "?c", .var "?p"] }, { pred := "ontray", args := [.var "?s", .var "?t"] }, { pred := "at", args := [.var "?t", .var "?p"] }],
    add := [{ pred := "served", args := [.var "?c"] }],
    del := [{ pred := "ontray", args := [.var "?s", .var "?t"] }],
    cost := 1 }

abbrev action5 : Action :=
  { name := "move_tray",
    params := [{ name := "?t", type := "tray" }, { name := "?p1", type := "place" }, { name := "?p2", type := "place" }],
    pre := [{ pred := "at", args := [.var "?t", .var "?p1"] }],
    add := [{ pred := "at", args := [.var "?t", .var "?p2"] }],
    del := [{ pred := "at", args := [.var "?t", .var "?p1"] }],
    cost := 1 }

abbrev actions : List Action := [action0, action1, action2, action3, action4, action5]

def domain : Domain :=
  { name := "childsnack",
    requirements := [":typing", ":equality"],
    types := [{ name := "child", parent := "object" }, { name := "bread-portion", parent := "object" }, { name := "content-portion", parent := "object" }, { name := "sandwich", parent := "object" }, { name := "tray", parent := "object" }, { name := "place", parent := "object" }],
    constants := [{ name := "kitchen", type := "place" }],
    predicates := [{ name := "at_kitchen_bread", params := [{ name := "?b", type := "bread-portion" }] }, { name := "at_kitchen_content", params := [{ name := "?c", type := "content-portion" }] }, { name := "at_kitchen_sandwich", params := [{ name := "?s", type := "sandwich" }] }, { name := "no_gluten_bread", params := [{ name := "?b", type := "bread-portion" }] }, { name := "no_gluten_content", params := [{ name := "?c", type := "content-portion" }] }, { name := "ontray", params := [{ name := "?s", type := "sandwich" }, { name := "?t", type := "tray" }] }, { name := "no_gluten_sandwich", params := [{ name := "?s", type := "sandwich" }] }, { name := "allergic_gluten", params := [{ name := "?c", type := "child" }] }, { name := "not_allergic_gluten", params := [{ name := "?c", type := "child" }] }, { name := "served", params := [{ name := "?c", type := "child" }] }, { name := "waiting", params := [{ name := "?c", type := "child" }, { name := "?p", type := "place" }] }, { name := "at", params := [{ name := "?t", type := "tray" }, { name := "?p", type := "place" }] }, { name := "notexist", params := [{ name := "?s", type := "sandwich" }] }],
    actions := actions }

end Planner.GeneratedDomains.Childsnack
