/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Ferry

open Planner.Pddl

abbrev action0 : Action :=
  { name := "sail",
    params := [{ name := "?from", type := "location" }, { name := "?to", type := "location" }],
    pre := [{ pred := "at-ferry", args := [.var "?from"] }, { pred := "not-at-ferry", args := [.var "?to"] }],
    add := [{ pred := "at-ferry", args := [.var "?to"] }, { pred := "not-at-ferry", args := [.var "?from"] }],
    del := [{ pred := "not-at-ferry", args := [.var "?to"] }, { pred := "at-ferry", args := [.var "?from"] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "board",
    params := [{ name := "?car", type := "car" }, { name := "?loc", type := "location" }],
    pre := [{ pred := "at", args := [.var "?car", .var "?loc"] }, { pred := "at-ferry", args := [.var "?loc"] }, { pred := "empty-ferry", args := [] }],
    add := [{ pred := "on", args := [.var "?car"] }],
    del := [{ pred := "at", args := [.var "?car", .var "?loc"] }, { pred := "empty-ferry", args := [] }],
    cost := 1 }

abbrev action2 : Action :=
  { name := "debark",
    params := [{ name := "?car", type := "car" }, { name := "?loc", type := "location" }],
    pre := [{ pred := "on", args := [.var "?car"] }, { pred := "at-ferry", args := [.var "?loc"] }],
    add := [{ pred := "at", args := [.var "?car", .var "?loc"] }, { pred := "empty-ferry", args := [] }],
    del := [{ pred := "on", args := [.var "?car"] }],
    cost := 1 }

abbrev actions : List Action := [action0, action1, action2]

def domain : Domain :=
  { name := "ferry",
    requirements := [":strips", ":typing"],
    types := [{ name := "car", parent := "object" }, { name := "location", parent := "object" }],
    constants := [],
    predicates := [{ name := "at-ferry", params := [{ name := "?x0", type := "location" }] }, { name := "at", params := [{ name := "?x0", type := "car" }, { name := "?x1", type := "location" }] }, { name := "empty-ferry", params := [] }, { name := "on", params := [{ name := "?x0", type := "car" }] }, { name := "not-at-ferry", params := [{ name := "?x0", type := "location" }] }],
    actions := actions }

end Planner.GeneratedDomains.Ferry
