/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Floortile

open Planner.Pddl

abbrev action0 : Action :=
  { name := "change_color",
    params := [{ name := "?r", type := "robot" }, { name := "?c", type := "color" }, { name := "?c2", type := "color" }],
    pre := [{ pred := "robot-has", args := [.var "?r", .var "?c"] }, { pred := "available-color", args := [.var "?c2"] }],
    add := [{ pred := "robot-has", args := [.var "?r", .var "?c2"] }],
    del := [{ pred := "robot-has", args := [.var "?r", .var "?c"] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "paint_up",
    params := [{ name := "?r", type := "robot" }, { name := "?y", type := "tile" }, { name := "?x", type := "tile" }, { name := "?c", type := "color" }],
    pre := [{ pred := "robot-has", args := [.var "?r", .var "?c"] }, { pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "up", args := [.var "?y", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    add := [{ pred := "painted", args := [.var "?y", .var "?c"] }],
    del := [{ pred := "clear", args := [.var "?y"] }],
    cost := 1 }

abbrev action2 : Action :=
  { name := "paint_down",
    params := [{ name := "?r", type := "robot" }, { name := "?y", type := "tile" }, { name := "?x", type := "tile" }, { name := "?c", type := "color" }],
    pre := [{ pred := "robot-has", args := [.var "?r", .var "?c"] }, { pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "down", args := [.var "?y", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    add := [{ pred := "painted", args := [.var "?y", .var "?c"] }],
    del := [{ pred := "clear", args := [.var "?y"] }],
    cost := 1 }

abbrev action3 : Action :=
  { name := "move_up",
    params := [{ name := "?r", type := "robot" }, { name := "?x", type := "tile" }, { name := "?y", type := "tile" }],
    pre := [{ pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "up", args := [.var "?y", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    add := [{ pred := "robot-at", args := [.var "?r", .var "?y"] }, { pred := "clear", args := [.var "?x"] }],
    del := [{ pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    cost := 1 }

abbrev action4 : Action :=
  { name := "move_down",
    params := [{ name := "?r", type := "robot" }, { name := "?x", type := "tile" }, { name := "?y", type := "tile" }],
    pre := [{ pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "down", args := [.var "?y", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    add := [{ pred := "robot-at", args := [.var "?r", .var "?y"] }, { pred := "clear", args := [.var "?x"] }],
    del := [{ pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    cost := 1 }

abbrev action5 : Action :=
  { name := "move_right",
    params := [{ name := "?r", type := "robot" }, { name := "?x", type := "tile" }, { name := "?y", type := "tile" }],
    pre := [{ pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "right", args := [.var "?y", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    add := [{ pred := "robot-at", args := [.var "?r", .var "?y"] }, { pred := "clear", args := [.var "?x"] }],
    del := [{ pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    cost := 1 }

abbrev action6 : Action :=
  { name := "move_left",
    params := [{ name := "?r", type := "robot" }, { name := "?x", type := "tile" }, { name := "?y", type := "tile" }],
    pre := [{ pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "left", args := [.var "?y", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    add := [{ pred := "robot-at", args := [.var "?r", .var "?y"] }, { pred := "clear", args := [.var "?x"] }],
    del := [{ pred := "robot-at", args := [.var "?r", .var "?x"] }, { pred := "clear", args := [.var "?y"] }],
    cost := 1 }

abbrev actions : List Action := [action0, action1, action2, action3, action4, action5, action6]

def domain : Domain :=
  { name := "floortile",
    requirements := [":typing"],
    types := [{ name := "robot", parent := "object" }, { name := "tile", parent := "object" }, { name := "color", parent := "object" }],
    constants := [],
    predicates := [{ name := "robot-at", params := [{ name := "?r", type := "robot" }, { name := "?x", type := "tile" }] }, { name := "up", params := [{ name := "?x", type := "tile" }, { name := "?y", type := "tile" }] }, { name := "down", params := [{ name := "?x", type := "tile" }, { name := "?y", type := "tile" }] }, { name := "right", params := [{ name := "?x", type := "tile" }, { name := "?y", type := "tile" }] }, { name := "left", params := [{ name := "?x", type := "tile" }, { name := "?y", type := "tile" }] }, { name := "clear", params := [{ name := "?x", type := "tile" }] }, { name := "painted", params := [{ name := "?x", type := "tile" }, { name := "?c", type := "color" }] }, { name := "robot-has", params := [{ name := "?r", type := "robot" }, { name := "?c", type := "color" }] }, { name := "available-color", params := [{ name := "?c", type := "color" }] }, { name := "free-color", params := [{ name := "?r", type := "robot" }] }],
    actions := actions }

end Planner.GeneratedDomains.Floortile
