/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Miconic

open Planner.Pddl

abbrev action0 : Action :=
  { name := "board",
    params := [{ name := "?f", type := "floor" }, { name := "?p", type := "passenger" }],
    pre := [{ pred := "lift-at", args := [.var "?f"] }, { pred := "origin", args := [.var "?p", .var "?f"] }],
    add := [{ pred := "boarded", args := [.var "?p"] }],
    del := [{ pred := "origin", args := [.var "?p", .var "?f"] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "depart",
    params := [{ name := "?f", type := "floor" }, { name := "?p", type := "passenger" }],
    pre := [{ pred := "lift-at", args := [.var "?f"] }, { pred := "destin", args := [.var "?p", .var "?f"] }, { pred := "boarded", args := [.var "?p"] }],
    add := [{ pred := "served", args := [.var "?p"] }],
    del := [{ pred := "boarded", args := [.var "?p"] }],
    cost := 1 }

abbrev action2 : Action :=
  { name := "up",
    params := [{ name := "?f1", type := "floor" }, { name := "?f2", type := "floor" }],
    pre := [{ pred := "lift-at", args := [.var "?f1"] }, { pred := "above", args := [.var "?f1", .var "?f2"] }],
    add := [{ pred := "lift-at", args := [.var "?f2"] }],
    del := [{ pred := "lift-at", args := [.var "?f1"] }],
    cost := 1 }

abbrev action3 : Action :=
  { name := "down",
    params := [{ name := "?f1", type := "floor" }, { name := "?f2", type := "floor" }],
    pre := [{ pred := "lift-at", args := [.var "?f1"] }, { pred := "above", args := [.var "?f2", .var "?f1"] }],
    add := [{ pred := "lift-at", args := [.var "?f2"] }],
    del := [{ pred := "lift-at", args := [.var "?f1"] }],
    cost := 1 }

abbrev actions : List Action := [action0, action1, action2, action3]

def domain : Domain :=
  { name := "miconic",
    requirements := [":strips", ":typing"],
    types := [{ name := "passenger", parent := "object" }, { name := "floor", parent := "object" }],
    constants := [],
    predicates := [{ name := "origin", params := [{ name := "?person", type := "passenger" }, { name := "?floor", type := "floor" }] }, { name := "destin", params := [{ name := "?person", type := "passenger" }, { name := "?floor", type := "floor" }] }, { name := "above", params := [{ name := "?floor1", type := "floor" }, { name := "?floor2", type := "floor" }] }, { name := "boarded", params := [{ name := "?person", type := "passenger" }] }, { name := "served", params := [{ name := "?person", type := "passenger" }] }, { name := "lift-at", params := [{ name := "?floor", type := "floor" }] }],
    actions := actions }

end Planner.GeneratedDomains.Miconic
