/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Satellite

open Planner.Pddl

abbrev action0 : Action :=
  { name := "turn_to",
    params := [{ name := "?s", type := "satellite" }, { name := "?d_new", type := "direction" }, { name := "?d_prev", type := "direction" }],
    pre := [{ pred := "pointing", args := [.var "?s", .var "?d_prev"] }, { pred := "not-pointing", args := [.var "?s", .var "?d_new"] }],
    add := [{ pred := "pointing", args := [.var "?s", .var "?d_new"] }, { pred := "not-pointing", args := [.var "?s", .var "?d_prev"] }],
    del := [{ pred := "not-pointing", args := [.var "?s", .var "?d_new"] }, { pred := "pointing", args := [.var "?s", .var "?d_prev"] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "switch_on",
    params := [{ name := "?i", type := "instrument" }, { name := "?s", type := "satellite" }],
    pre := [{ pred := "on_board", args := [.var "?i", .var "?s"] }, { pred := "power_avail", args := [.var "?s"] }],
    add := [{ pred := "power_on", args := [.var "?i"] }],
    del := [{ pred := "calibrated", args := [.var "?i"] }, { pred := "power_avail", args := [.var "?s"] }],
    cost := 1 }

abbrev action2 : Action :=
  { name := "switch_off",
    params := [{ name := "?i", type := "instrument" }, { name := "?s", type := "satellite" }],
    pre := [{ pred := "on_board", args := [.var "?i", .var "?s"] }, { pred := "power_on", args := [.var "?i"] }],
    add := [{ pred := "power_avail", args := [.var "?s"] }],
    del := [{ pred := "power_on", args := [.var "?i"] }],
    cost := 1 }

abbrev action3 : Action :=
  { name := "calibrate",
    params := [{ name := "?s", type := "satellite" }, { name := "?i", type := "instrument" }, { name := "?d", type := "direction" }],
    pre := [{ pred := "on_board", args := [.var "?i", .var "?s"] }, { pred := "calibration_target", args := [.var "?i", .var "?d"] }, { pred := "pointing", args := [.var "?s", .var "?d"] }, { pred := "power_on", args := [.var "?i"] }],
    add := [{ pred := "calibrated", args := [.var "?i"] }],
    del := [],
    cost := 1 }

abbrev action4 : Action :=
  { name := "take_image",
    params := [{ name := "?s", type := "satellite" }, { name := "?d", type := "direction" }, { name := "?i", type := "instrument" }, { name := "?m", type := "mode" }],
    pre := [{ pred := "calibrated", args := [.var "?i"] }, { pred := "on_board", args := [.var "?i", .var "?s"] }, { pred := "supports", args := [.var "?i", .var "?m"] }, { pred := "power_on", args := [.var "?i"] }, { pred := "pointing", args := [.var "?s", .var "?d"] }],
    add := [{ pred := "have_image", args := [.var "?d", .var "?m"] }],
    del := [],
    cost := 1 }

abbrev actions : List Action := [action0, action1, action2, action3, action4]

def domain : Domain :=
  { name := "satellite",
    requirements := [":strips", ":typing"],
    types := [{ name := "satellite", parent := "object" }, { name := "direction", parent := "object" }, { name := "instrument", parent := "object" }, { name := "mode", parent := "object" }],
    constants := [],
    predicates := [{ name := "on_board", params := [{ name := "?x0", type := "instrument" }, { name := "?x1", type := "satellite" }] }, { name := "supports", params := [{ name := "?x0", type := "instrument" }, { name := "?x1", type := "mode" }] }, { name := "pointing", params := [{ name := "?x0", type := "satellite" }, { name := "?x1", type := "direction" }] }, { name := "power_avail", params := [{ name := "?x0", type := "satellite" }] }, { name := "power_on", params := [{ name := "?x0", type := "instrument" }] }, { name := "calibrated", params := [{ name := "?x0", type := "instrument" }] }, { name := "have_image", params := [{ name := "?x0", type := "direction" }, { name := "?x1", type := "mode" }] }, { name := "calibration_target", params := [{ name := "?x0", type := "instrument" }, { name := "?x1", type := "direction" }] }, { name := "not-pointing", params := [{ name := "?x0", type := "satellite" }, { name := "?x1", type := "direction" }] }],
    actions := actions }

end Planner.GeneratedDomains.Satellite
