/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Sokoban

open Planner.Pddl

abbrev action0 : Action :=
  { name := "move",
    params := [{ name := "?from", type := "location" }, { name := "?to", type := "location" }, { name := "?dir", type := "direction" }],
    pre := [{ pred := "clear", args := [.var "?to"] }, { pred := "at-robot", args := [.var "?from"] }, { pred := "adjacent", args := [.var "?from", .var "?to", .var "?dir"] }],
    add := [{ pred := "at-robot", args := [.var "?to"] }],
    del := [{ pred := "at-robot", args := [.var "?from"] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "push",
    params := [{ name := "?rloc", type := "location" }, { name := "?bloc", type := "location" }, { name := "?floc", type := "location" }, { name := "?dir", type := "direction" }, { name := "?b", type := "box" }],
    pre := [{ pred := "at-robot", args := [.var "?rloc"] }, { pred := "at", args := [.var "?b", .var "?bloc"] }, { pred := "clear", args := [.var "?floc"] }, { pred := "adjacent", args := [.var "?rloc", .var "?bloc", .var "?dir"] }, { pred := "adjacent", args := [.var "?bloc", .var "?floc", .var "?dir"] }],
    add := [{ pred := "at-robot", args := [.var "?bloc"] }, { pred := "at", args := [.var "?b", .var "?floc"] }, { pred := "clear", args := [.var "?bloc"] }],
    del := [{ pred := "at-robot", args := [.var "?rloc"] }, { pred := "at", args := [.var "?b", .var "?bloc"] }, { pred := "clear", args := [.var "?floc"] }],
    cost := 1 }

abbrev actions : List Action := [action0, action1]

def domain : Domain :=
  { name := "sokoban",
    requirements := [":typing"],
    types := [{ name := "location", parent := "object" }, { name := "direction", parent := "object" }, { name := "box", parent := "object" }],
    constants := [{ name := "down", type := "direction" }, { name := "up", type := "direction" }, { name := "left", type := "direction" }, { name := "right", type := "direction" }],
    predicates := [{ name := "at-robot", params := [{ name := "?l", type := "location" }] }, { name := "at", params := [{ name := "?o", type := "box" }, { name := "?l", type := "location" }] }, { name := "adjacent", params := [{ name := "?l1", type := "location" }, { name := "?l2", type := "location" }, { name := "?d", type := "direction" }] }, { name := "clear", params := [{ name := "?l", type := "location" }] }],
    actions := actions }

end Planner.GeneratedDomains.Sokoban
