/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Spanner

open Planner.Pddl

abbrev action0 : Action :=
  { name := "walk",
    params := [{ name := "?start", type := "location" }, { name := "?end", type := "location" }, { name := "?m", type := "man" }],
    pre := [{ pred := "at", args := [.var "?m", .var "?start"] }, { pred := "link", args := [.var "?start", .var "?end"] }],
    add := [{ pred := "at", args := [.var "?m", .var "?end"] }],
    del := [{ pred := "at", args := [.var "?m", .var "?start"] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "pickup_spanner",
    params := [{ name := "?l", type := "location" }, { name := "?s", type := "spanner" }, { name := "?m", type := "man" }],
    pre := [{ pred := "at", args := [.var "?m", .var "?l"] }, { pred := "at", args := [.var "?s", .var "?l"] }],
    add := [{ pred := "carrying", args := [.var "?m", .var "?s"] }],
    del := [{ pred := "at", args := [.var "?s", .var "?l"] }],
    cost := 1 }

abbrev action2 : Action :=
  { name := "tighten_nut",
    params := [{ name := "?l", type := "location" }, { name := "?s", type := "spanner" }, { name := "?m", type := "man" }, { name := "?n", type := "nut" }],
    pre := [{ pred := "at", args := [.var "?m", .var "?l"] }, { pred := "at", args := [.var "?n", .var "?l"] }, { pred := "carrying", args := [.var "?m", .var "?s"] }, { pred := "usable", args := [.var "?s"] }, { pred := "loose", args := [.var "?n"] }],
    add := [{ pred := "tightened", args := [.var "?n"] }],
    del := [{ pred := "loose", args := [.var "?n"] }, { pred := "usable", args := [.var "?s"] }],
    cost := 1 }

abbrev actions : List Action := [action0, action1, action2]

def domain : Domain :=
  { name := "spanner",
    requirements := [":typing", ":strips"],
    types := [{ name := "location", parent := "object" }, { name := "locatable", parent := "object" }, { name := "man", parent := "locatable" }, { name := "nut", parent := "locatable" }, { name := "spanner", parent := "locatable" }],
    constants := [],
    predicates := [{ name := "at", params := [{ name := "?m", type := "locatable" }, { name := "?l", type := "location" }] }, { name := "carrying", params := [{ name := "?m", type := "man" }, { name := "?s", type := "spanner" }] }, { name := "usable", params := [{ name := "?s", type := "spanner" }] }, { name := "link", params := [{ name := "?l1", type := "location" }, { name := "?l2", type := "location" }] }, { name := "tightened", params := [{ name := "?n", type := "nut" }] }, { name := "loose", params := [{ name := "?n", type := "nut" }] }],
    actions := actions }

end Planner.GeneratedDomains.Spanner
