/-
Generated from validated PDDL by DomainSchemaGen.lean.
Do not edit this file.  Run scripts/generate_domains.sh instead.
-/
import Planner.Pddl.Syntax

namespace Planner.GeneratedDomains.Transport

open Planner.Pddl

abbrev action0 : Action :=
  { name := "drive",
    params := [{ name := "?v", type := "vehicle" }, { name := "?l1", type := "location" }, { name := "?l2", type := "location" }],
    pre := [{ pred := "at", args := [.var "?v", .var "?l1"] }, { pred := "road", args := [.var "?l1", .var "?l2"] }],
    add := [{ pred := "at", args := [.var "?v", .var "?l2"] }],
    del := [{ pred := "at", args := [.var "?v", .var "?l1"] }],
    cost := 1 }

abbrev action1 : Action :=
  { name := "pick-up",
    params := [{ name := "?v", type := "vehicle" }, { name := "?l", type := "location" }, { name := "?p", type := "package" }, { name := "?s1", type := "size" }, { name := "?s2", type := "size" }],
    pre := [{ pred := "at", args := [.var "?v", .var "?l"] }, { pred := "at", args := [.var "?p", .var "?l"] }, { pred := "capacity-predecessor", args := [.var "?s1", .var "?s2"] }, { pred := "capacity", args := [.var "?v", .var "?s2"] }],
    add := [{ pred := "in", args := [.var "?p", .var "?v"] }, { pred := "capacity", args := [.var "?v", .var "?s1"] }],
    del := [{ pred := "at", args := [.var "?p", .var "?l"] }, { pred := "capacity", args := [.var "?v", .var "?s2"] }],
    cost := 1 }

abbrev action2 : Action :=
  { name := "drop",
    params := [{ name := "?v", type := "vehicle" }, { name := "?l", type := "location" }, { name := "?p", type := "package" }, { name := "?s1", type := "size" }, { name := "?s2", type := "size" }],
    pre := [{ pred := "at", args := [.var "?v", .var "?l"] }, { pred := "in", args := [.var "?p", .var "?v"] }, { pred := "capacity-predecessor", args := [.var "?s1", .var "?s2"] }, { pred := "capacity", args := [.var "?v", .var "?s1"] }],
    add := [{ pred := "at", args := [.var "?p", .var "?l"] }, { pred := "capacity", args := [.var "?v", .var "?s2"] }],
    del := [{ pred := "in", args := [.var "?p", .var "?v"] }, { pred := "capacity", args := [.var "?v", .var "?s1"] }],
    cost := 1 }

abbrev actions : List Action := [action0, action1, action2]

def domain : Domain :=
  { name := "transport",
    requirements := [":typing"],
    types := [{ name := "size", parent := "object" }, { name := "location", parent := "object" }, { name := "locatable", parent := "object" }, { name := "vehicle", parent := "locatable" }, { name := "package", parent := "locatable" }],
    constants := [],
    predicates := [{ name := "road", params := [{ name := "?l1", type := "location" }, { name := "?l2", type := "location" }] }, { name := "at", params := [{ name := "?x", type := "locatable" }, { name := "?v", type := "location" }] }, { name := "in", params := [{ name := "?x", type := "package" }, { name := "?v", type := "vehicle" }] }, { name := "capacity", params := [{ name := "?v", type := "vehicle" }, { name := "?s1", type := "size" }] }, { name := "capacity-predecessor", params := [{ name := "?s1", type := "size" }, { name := "?s2", type := "size" }] }],
    actions := actions }

end Planner.GeneratedDomains.Transport
