/-
Generate the canonical Lean representation of a validated PDDL domain.

The generated module is runtime code.  Proof modules may give its positional
actions convenient domain-specific aliases, but they never reproduce the action
records by hand.
-/
import Planner.Pddl.Parser
import Planner.Pddl.Validation

open Planner.Pddl

private def usage : String :=
  "usage: domain_schema_gen [--check] DOMAIN.pddl MODULE_NAME OUTPUT.lean"

private def leanString (s : String) : String := reprStr s

private def renderList (render : α → String) (xs : List α) : String :=
  "[" ++ ", ".intercalate (xs.map render) ++ "]"

private def renderTypedName (x : TypedName) : String :=
  "{ name := " ++ leanString x.name ++ ", type := " ++ leanString x.type ++ " }"

private def renderTypeDecl (x : TypeDecl) : String :=
  "{ name := " ++ leanString x.name ++ ", parent := " ++ leanString x.parent ++ " }"

private def renderPredicate (x : Predicate) : String :=
  "{ name := " ++ leanString x.name ++
    ", params := " ++ renderList renderTypedName x.params ++ " }"

private def renderTerm : Term → String
  | .var name => s!".var {leanString name}"
  | .const name => s!".const {leanString name}"

private def renderAtom (x : Atom) : String :=
  "{ pred := " ++ leanString x.pred ++
    ", args := " ++ renderList renderTerm x.args ++ " }"

private def renderAction (index : Nat) (x : Action) : String :=
  s!"abbrev action{index} : Action :=\n" ++
  "  { name := " ++ leanString x.name ++ ",\n" ++
  s!"    params := {renderList renderTypedName x.params},\n" ++
  s!"    pre := {renderList renderAtom x.pre},\n" ++
  s!"    add := {renderList renderAtom x.add},\n" ++
  s!"    del := {renderList renderAtom x.del},\n" ++
  s!"    cost := {x.cost} " ++ "}\n"

private def validModuleName (name : String) : Bool :=
  !name.isEmpty && name.toList.all fun c => c.isAlphanum || c == '_'

private def renderModule (moduleName : String) (d : Domain) : String :=
  let actionDefs := String.intercalate "\n" <|
    (d.actions.zipIdx.map fun (action, index) => renderAction index action)
  let actionNames := renderList (fun index : Nat => s!"action{index}")
    (List.range d.actions.length)
  "/-\n" ++
  "Generated from validated PDDL by DomainSchemaGen.lean.\n" ++
  "Do not edit this file.  Run scripts/generate_domains.sh instead.\n" ++
  "-/\n" ++
  "import Planner.Pddl.Syntax\n\n" ++
  s!"namespace Planner.GeneratedDomains.{moduleName}\n\n" ++
  "open Planner.Pddl\n\n" ++
  actionDefs ++ "\n" ++
  s!"abbrev actions : List Action := {actionNames}\n\n" ++
  "def domain : Domain :=\n" ++
  "  { name := " ++ leanString d.name ++ ",\n" ++
  s!"    requirements := {renderList leanString d.requirements},\n" ++
  s!"    types := {renderList renderTypeDecl d.types},\n" ++
  s!"    constants := {renderList renderTypedName d.constants},\n" ++
  s!"    predicates := {renderList renderPredicate d.predicates},\n" ++
  "    actions := actions }\n\n" ++
  s!"end Planner.GeneratedDomains.{moduleName}\n"

private structure Options where
  check : Bool := false
  domainFile : String
  moduleName : String
  outputFile : String

private def parseArgs : List String → Except String Options
  | [domainFile, moduleName, outputFile] =>
      .ok { domainFile, moduleName, outputFile }
  | ["--check", domainFile, moduleName, outputFile] =>
      .ok { check := true, domainFile, moduleName, outputFile }
  | _ => .error usage

def main (args : List String) : IO UInt32 := do
  let options ← match parseArgs args with
    | .ok options => pure options
    | .error error => IO.eprintln error; return 2
  unless validModuleName options.moduleName do
    IO.eprintln s!"invalid Lean module name '{options.moduleName}'"
    return 2
  let source ← IO.FS.readFile options.domainFile
  let domain ← match parseDomain source >>= validateDomain with
    | .ok domain => pure domain
    | .error error =>
        IO.eprintln s!"error in {options.domainFile}: {error}"
        return 1
  let generated := renderModule options.moduleName domain
  if options.check then
    let existing? ← try
      some <$> IO.FS.readFile options.outputFile
    catch _ => pure none
    let some existing := existing? | do
      IO.eprintln s!"generated domain module is missing: {options.outputFile}"
      return 1
    if existing == generated then
      IO.println s!"Generated domain module is current: {options.outputFile}"
      return 0
    else
      IO.eprintln s!"generated domain module is stale: {options.outputFile}"
      IO.eprintln "Run scripts/generate_domains.sh and commit the result."
      return 1
  else
    IO.FS.writeFile options.outputFile generated
    IO.println s!"Generated {options.outputFile}"
    return 0
