/-
Proofs about the planner.  Each file here corresponds to one file of `Planner/`.
-/
import Proofs.State
import Proofs.Validation
import Proofs.Task
import Proofs.Finite
import Proofs.Properties
import Proofs.Combinators
import Proofs.Certificates
import Proofs.SchemaSupport
import Proofs.Distance
import Proofs.Grounding
import Proofs.Semantics
import Proofs.GroundingCorrect
import Proofs.GroundingSound
import Proofs.GroundingComplete
import Proofs.CompileSupport
import Proofs.FactTables
import Proofs.Reachable
import Proofs.Relevance
import Proofs.StepView
import Proofs.LiftedHeuristic
import Proofs.Heuristic
import Proofs.LiftedSimple
import Proofs.ExampleHeuristics.Base
import Proofs.ExampleHeuristics.SchemaBase
import Proofs.ExampleHeuristics.Blind
import Proofs.Search.OpenList
import Proofs.Search.Node
import Proofs.Search.AStar
import Proofs.Search.Fuel
import Proofs.Domains.BlocksworldSimple
import Proofs.Domains.Blocksworld
import Proofs.Domains.ChildsnackSimple
import Proofs.Domains.Childsnack
import Proofs.Domains.FerrySimple
import Proofs.Domains.Ferry
import Proofs.Domains.FloortileSimple
import Proofs.Domains.Floortile
import Proofs.Domains.MiconicSimple
import Proofs.Domains.Miconic
import Proofs.Domains.RoversSimple
import Proofs.Domains.Rovers
import Proofs.Domains.SatelliteSimple
import Proofs.Domains.Satellite
import Proofs.Domains.SokobanDomain
import Proofs.Domains.SokobanSimple
import Proofs.Domains.Sokoban
import Proofs.Domains.SpannerSimple
import Proofs.Domains.Spanner
import Proofs.Domains.TransportSimple
import Proofs.Domains.Transport
